
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/mingw64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 6.2.9200 - AMD64
...
